led.toggle(2, 2)
let time = 200
led.toggle(0, 0)
basic.pause(time)
led.toggle(1, 0)
basic.pause(time)
led.toggle(2, 0)
basic.pause(time)
led.toggle(3, 0)
basic.forever(function () {
    basic.pause(time)
    led.toggle(4, 0)
    led.toggle(0, 0)
    basic.pause(time)
    led.toggle(4, 1)
    led.toggle(1, 0)
    basic.pause(time)
    led.toggle(4, 2)
    led.toggle(2, 0)
    basic.pause(time)
    led.toggle(4, 3)
    led.toggle(3, 0)
    basic.pause(time)
    led.toggle(4, 4)
    led.toggle(4, 0)
    basic.pause(time)
    led.toggle(3, 4)
    led.toggle(4, 1)
    basic.pause(time)
    led.toggle(2, 4)
    led.toggle(4, 2)
    basic.pause(time)
    led.toggle(1, 4)
    led.toggle(4, 3)
    basic.pause(time)
    led.toggle(0, 4)
    led.toggle(4, 4)
    basic.pause(time)
    led.toggle(0, 3)
    led.toggle(3, 4)
    basic.pause(time)
    led.toggle(0, 2)
    led.toggle(2, 4)
    basic.pause(time)
    led.toggle(0, 1)
    led.toggle(1, 4)
    basic.pause(time)
    led.toggle(0, 0)
    led.toggle(0, 4)
    basic.pause(time)
    led.toggle(1, 0)
    led.toggle(0, 3)
    basic.pause(time)
    led.toggle(2, 0)
    led.toggle(0, 2)
    basic.pause(time)
    led.toggle(3, 0)
    led.toggle(0, 1)
})
